name: pr

on: pull_request

jobs:
  build-test:
    name: Build and run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set-up Node
        uses: actions/setup-node@v1
        with:
          node-version: "16"
      - run: npm install
      - run: npm test
      - run: npm run build
